spring:
  security:
    oauth2:
      client:
        registration:
          github:
            # this is my personal github client-id
            clientId: # add your id here
            clientSecret: # add your secret here